# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
use_frameworks!

target 'SyllaSync' do

pod 'Google/SignIn'
pod 'CVCalendar', :git => 'https://github.com/Mozharovsky/CVCalendar', :branch => 'master'

end

target 'SyllaSyncTests' do

pod 'Google/SignIn'
pod 'CVCalendar', :git => 'https://github.com/Mozharovsky/CVCalendar', :branch => 'master'

end

