# Uncomment this line to define a global platform for your project
 platform :ios, '9.1'
use_frameworks!

target 'SyllaSync' do

#pod 'CVCalendar', :git => 'https://github.com/Mozharovsky/CVCalendar', :branch => 'master'
pod 'CVCalendar', '~> 1.2.7'
pod 'SwiftyJSON', '~> 2.3.0'

end

target 'SyllaSyncTests' do

#pod 'CVCalendar', :git => 'https://github.com/Mozharovsky/CVCalendar', :branch => 'master'
pod 'CVCalendar', '~> 1.2.7'
end

